### PR TITLE
BitcoinRPC initializer rework

### PR DESCRIPTION
**Pull request by bibajz**
This PR picks up the work outlined in #10 .

Get rid of `host`, `port` parameters in `BitcoinRPC.__init__` method and use `url` instead.

What do you think @schlunsen ?

### CODE REVIEW

**Comment by schlunsen** [comment]
@bibajz Looks good to me! Thanks again!

**Comment by bibajz** [comment]
Done!

Thank you very much for the effort and interest!
Libor

**Comment by schlunsen** [comment]
Great! Will you release to pypi as well?

**Comment by bibajz** [comment]
Hi! It is on pypi since yesterday. ;)

**Pull request merged**
